### ISSUE TITLE
InvalidArgumentError

### ISSUE THREAD

**Issue by qhtang21** [ShujinW/Deep-Video-Inpainting-Localization#1]
I changed the img size as 480*856 and got this error at line 229, how to solve it?
Thanks a lot!
InvalidArgumentError
2 root error(s) found.
  (0) Invalid argument: Incompatible shapes: [480,856] vs. [2,8,1,0,0]
	 [[node add (defined at /miniconda3/envs/365/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[Add_2/_79]]
  (1) Invalid argument: Incompatible shapes: [480,856] vs. [2,8,1,0,0]
	 [[node add (defined at /miniconda3/envs/365/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

**Comment by ShujinW** [comment]
您的邮件已收到，谢谢！
